DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS passages;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE passages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  auteur TEXT NOT NULL,
  livre TEXT NOT NULL,
  texte TEXT NOT NULL,
  annee_citation INTEGER,
  date_ajout TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  commentaire TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id)
);